PID_EXTRACTION_PROMPT = """
You are analyzing a P&ID (Piping and Instrumentation Diagram) page for an oil and gas facility.

COMPONENT DEFINITIONS (ISA 5.1 standard):
- PSV: Pressure Safety Valve
- PI: Pressure Indicator
- PDI: Pressure Differential Indicator
- PT: Pressure Transmitter
- LG: Level Gauge
- LI: Level Indicator
- LT: Level Transmitter
- LAH: Level Alarm High
- LAL: Level Alarm Low
- TI: Temperature Indicator
- TT: Temperature Transmitter
- TC: Temperature Controller
- MV: Manual Valve
- SDV: Shutdown Valve

EQUIPMENT TYPES:
- Vessels/Separators: cylindrical vessels with nozzles
- Heat Exchangers: shell and tube or air cooled units
- Pumps: centrifugal or submersible units
- Coolers: air cooled heat exchangers

LINE TYPES:
- Thick solid lines: major process pipes (extract these)
- Thin solid lines: instrument connections (ignore)
- Dashed lines: signal lines (ignore)

EXTRACTION RULES:
LEVEL 1 - MAJOR EQUIPMENT:
Extract tag ID, type, design pressure (PSIG), operating pressure (PSIG),
design temperature (F), and page number.

LEVEL 2 - INSTRUMENTS:
Extract tag ID, type, parent equipment, set point if visible,
size if visible, page number, and confidence (high/medium/low).

LEVEL 3 - MANUAL VALVES:
Extract ALL MV- tags. Include confidence score.
Never skip a valve — use low confidence if label is hard to read.

LEVEL 4 - NAMED PIPES:
Extract pipe ID, size in inches, page number.
Pipes appear in both components and connections arrays.

CONNECTIONS:
For each named pipe, show what equipment it connects from and to.
Include valve IDs on that pipe in a valves array.
is_external: true ONLY if endpoint equipment is not shown on this page.

Return ONLY valid JSON, no markdown, no preamble:
{
    "components": [
        {
            "id": "F-715A",
            "type": "particulate_filter_separator",
            "level": 1,
            "page": 1,
            "design_pressure_psig": 275,
            "operating_pressure_psig": 250,
            "design_temp_f": 100
        },
        {
            "id": "PSV-715A",
            "type": "pressure_safety_valve",
            "level": 2,
            "page": 1,
            "parent_equipment": "F-715A",
            "set_point_psig": 275,
            "size": "3/4x1",
            "confidence": "high"
        },
        {
            "id": "MV-715-01",
            "type": "manual_valve",
            "level": 3,
            "page": 1,
            "parent_equipment": "F-715A",
            "parent_pipe": "6-PL-2000-D",
            "confidence": "high"
        },
        {
            "id": "6-PL-2000-D",
            "type": "pipe",
            "level": 4,
            "page": 1,
            "size_inches": 6
        }
    ],
    "connections": [
        {
            "from": "V-710",
            "to": "F-715A",
            "pipe_id": "6-PL-2000-D",
            "size_inches": 6,
            "is_external": true,
            "valves": ["MV-715-01"]
        }
    ],
    "summary": {
        "total_components": 0,
        "total_connections": 0,
        "components_by_level": {
            "level_1": 0,
            "level_2": 0,
            "level_3": 0,
            "level_4": 0
        }
    }
}
"""

PID_EXTRACTION_PROMPT_V2 = """
You are analyzing a P&ID (Piping and Instrumentation Diagram) page for an oil and gas facility and exporting data to be used
to construct a digital twin via a graph.  

You are identfying nodes and connections according to the following:

Components are anything that lines are connecting in the image, and will be represented as nodes in the graph. There are 
three "levels" of components: equpment, instruments, and valves. 

Each node will have four fields. The content of these fields will differ depending on what level the node is. For how to recognize each
level and the differences in their fields, see levels of components.

The four fields every node has:
- id_temp: a random UUID (generated by you)
- level: equipment, instrument, or valve
- component_name: differs by level
- metadata: dict that differs by level

Levels of components (from highest to lowest): 

1. Equipment. 
Equipment components typically have two refernces on the image. They have their component name underlined and in the largest font in the image. 
Here, they often have operating and / or maxiumum specifications under their title. Record these specifications by using context to infer what the value means, 
and store them in the metedata dict. Their level name is "equipment." Their component_name is the underlined name. 

2. Instruments.
Instruments are small circles connected to equipment or pipes by thin lines (thinner than process lines).
Inside each circle are 2-3 letters identifying the instrument type followed by a number (e.g. PI-715A, PSV-745).
Common letter codes:
- PSV: Pressure Safety Valve — circle with a spring/triangle actuator symbol above it
- PI: Pressure Indicator
- PDI: Pressure Differential Indicator  
- LG: Level Gauge — typically two connection points on the side of a vessel
- LT/PT/TT: Level/Pressure/Temperature Transmitter
- LAH/LAL: Level Alarm High/Low
- TC/TI: Temperature Controller/Indicator
Their level name is "instrument." Their component_name is the full tag (e.g. "PSV-715A").
Metadata fields:
- type: the instrument type derived from the letter code
- parent_component_name: the equipment or pipe it is connected to
- set_point: any visible set point or range value
- size: physical size if visible (common on PSVs e.g. "3/4x1")
- confidence: high/medium/low based on label readability

3. Valves.
Valves sit directly ON the thick process lines — unlike instruments which connect via thin lines.
They interrupt the line with a symbol:
- Bow-tie or X shape: manual gate/globe valve (most common, tagged MV-xxx)
- Bow-tie with actuator on top: control valve
- Bow-tie with circle on stem: ball valve
- Arrow pointing into line: check valve (flow direction only, no tag)
Extract ALL visible valve tags. Never skip — use low confidence if label is hard to read.
Their level name is "valve." Their component_name is the full tag (e.g. "MV-715-01").
Metadata fields:
- type: manual_valve, control_valve, check_valve, safety_valve
- parent_component_name: the equipment it is most closely associated with
- parent_pipe: the pipe line it sits on if identifiable
- confidence: high/medium/low based on label readability



EQUIPMENT TYPES:
- Vessels/Separators: cylindrical vessels with nozzles
- Heat Exchangers: shell and tube or air cooled units
- Pumps: centrifugal or submersible units
- Coolers: air cooled heat exchangers

LINE TYPES:
- Thick solid lines: major process pipes (extract these)
- Thin solid lines: instrument connections (ignore)
- Dashed lines: signal lines (ignore)

EXTRACTION RULES:
LEVEL 1 - EQUIPMENT:


Extract tag ID, type, design pressure (PSIG), operating pressure (PSIG),
design temperature (F), and page number.

LEVEL 2 - INSTRUMENTS:
Extract tag ID, type, parent equipment, set point if visible,
size if visible, page number, and confidence (high/medium/low).

LEVEL 3 - MANUAL VALVES:
Extract ALL MV- tags. Include confidence score.
Never skip a valve — use low confidence if label is hard to read.

LEVEL 4 - NAMED PIPES:
Extract pipe ID, size in inches, page number.
Pipes appear in both components and connections arrays.

CONNECTIONS:
For each named pipe, show what equipment it connects from and to.
Include valve IDs on that pipe in a valves array.
is_external: true ONLY if endpoint equipment is not shown on this page.

Return ONLY valid JSON, no markdown, no preamble:
{
    "components": [
        {
            "id": "F-715A",
            "type": "particulate_filter_separator",
            "level": 1,
            "page": 1,
            "design_pressure_psig": 275,
            "operating_pressure_psig": 250,
            "design_temp_f": 100
        },
        {
            "id": "PSV-715A",
            "type": "pressure_safety_valve",
            "level": 2,
            "page": 1,
            "parent_equipment": "F-715A",
            "set_point_psig": 275,
            "size": "3/4x1",
            "confidence": "high"
        },
        {
            "id": "MV-715-01",
            "type": "manual_valve",
            "level": 3,
            "page": 1,
            "parent_equipment": "F-715A",
            "parent_pipe": "6-PL-2000-D",
            "confidence": "high"
        },
        {
            "id": "6-PL-2000-D",
            "type": "pipe",
            "level": 4,
            "page": 1,
            "size_inches": 6
        }
    ],
    "connections": [
        {
            "from": "V-710",
            "to": "F-715A",
            "pipe_id": "6-PL-2000-D",
            "size_inches": 6,
            "is_external": true,
            "valves": ["MV-715-01"]
        }
    ],
    "summary": {
        "total_components": 0,
        "total_connections": 0,
        "components_by_level": {
            "level_1": 0,
            "level_2": 0,
            "level_3": 0,
            "level_4": 0
        }
    }
}
"""

PID_EXTRACTION_PROMPT_V3 = """
You are analyzing a P&ID (Piping and Instrumentation Diagram) for an oil and gas facility
and exporting data to construct a digital twin via a graph.

You are identifying nodes and connections. Every node and connection has a confidence field
(high/medium/low) based on how clearly it is identifiable in the image. No node exists in isolation. Specifically, each network of 
of nodes must be connected to at least one equipment node through its network. 

===========================
NODES
===========================

Every node has these four fields:
- id_temp: a generated UUID (you generate this)
- level: equipment / instrument / valve / connector / null (for off-page endpoints)
- component_name: differs by level (see below)
- metadata: dict of specs, infer meaning from context
- confidence: high / medium / low

---

LEVEL 1 — EQUIPMENT
Equipment is always a large vessel, exchanger, pump, or cooler with an underlined title. Equipment components typically have two references on the image. Once not visually attached to a particular component, but floating in a non crowded portion of the page.  
Here, they often have operating and / or maxiumum specifications under their title. Record these specifications by using context to infer what the value means, 
and store them in the metedata dict. Their level name is "equipment." Their component_name is the underlined name. 

- id_temp: generated UUID
- level: "equipment"
- component_name: the underlined name (e.g. "F-715A", "V-745")
- metadata: all visible specs — infer meaning from context (e.g. design pressure,
  operating pressure, design temperature, size, capacity)
- confidence: high / medium / low

---

LEVEL 2 — INSTRUMENTS
Instruments are small circles connected to equipment or pipes by thin lines.
Inside each circle are 2-3 letters identifying the instrument type followed by a number.
Common types:
- PSV: Pressure Safety Valve — circle with spring/triangle actuator above
- PI: Pressure Indicator
- PDI: Pressure Differential Indicator
- LG: Level Gauge — typically two connection points on vessel side
- LT/PT/TT: Level/Pressure/Temperature Transmitter
- LAH/LAL: Level Alarm High/Low
- TC/TI: Temperature Controller/Indicator

- id_temp: generated UUID
- level: "instrument"
- component_name: full tag (e.g. "PSV-715A", "PI-745")
- metadata: {
    type: instrument type from letter code,
    parent_component_name: equipment or pipe it connects to,
    set_point: any visible set point or range,
    size: physical size if visible (e.g. "3/4x1" on PSVs)
  }
- confidence: high / medium / low

---

LEVEL 3 — VALVES
Valves sit directly process lines, interrupting them with a symbol.
Common symbols:
- Bow-tie or X shape: manual gate/globe valve (tagged MV-xxx)
- Bow-tie with actuator on top: control valve
- Bow-tie with circle on stem: ball valve
- Arrow pointing into line: check valve

Extract ALL visible valve tags. Never skip — use low confidence if label is hard to read.

- id_temp: generated UUID
- level: "valve"
- component_name: full tag (e.g. "MV-715-01")
- metadata: {
    type: manual_valve / control_valve / check_valve / safety_valve,
    parent_component_name: closest equipment,
    parent_pipe: pipe line it sits on if identifiable
  }
- confidence: high / medium / low

---

CONNECTORS
Connectors are structural junction points with no real-world meaning.
They exist purely to maintain graph structure where lines meet.

Create a connector when:
- Three or more lines fully meet at a point (lines overlap completely, no gaps)
- An instrument line taps into a process line
- A pipe splits at a tee junction

Do NOT create a connector when:
- Two lines cross but one has a visible gap/hop at the intersection.
  This means the lines pass over each other without connecting.

- id_temp: generated UUID
- level: "connector"
- component_name: "connector"
- metadata: {description: brief description of what is joining here}
- confidence: high / medium / low

---

OFF-PAGE ENDPOINTS
If a pipe runs off the edge of the page, create a placeholder node.
If the same destination appears at multiple physical locations on the page,
create a separate placeholder for each location.

- id_temp: generated UUID
- level: null
- component_name: "off_page_endpoint"
- metadata: destination label if visible (e.g. "TO CLOSED DRAIN TANK")
- confidence: high / medium / low

===========================
CONNECTIONS
===========================

Every line segment between two nodes is one connection.

Line types:
- major_process: thick solid lines — main process flow
- minor_process: thin solid lines — instrument taps, small connections
- signal: dashed lines — pneumatic, electrical, or hydraulic signals

Fields:
- id_temp: generated UUID
- line_type: major_process / minor_process / signal
- start_id: id_temp of start node
- end_id: id_temp of end node
- pipeline: UUID shared across all segments of the same continuous pipe run.
  All segments split by valves or connectors share this UUID.
- metadata: any visible specs — pipe size, line number, insulation,
  flow direction, temperature rating. Infer meaning from context.
- confidence: high / medium / low

PIPE SEGMENTATION RULE:
If any component (valve, instrument, connector) sits in the middle of a pipe,
record it as two separate connection segments — one on each side of the component.
Both segments share the same pipeline UUID.

Example — valve MV-715-01 on pipe between V-710 and F-715A:
  segment 1: start=V-710 id, end=MV-715-01 id, pipeline=<shared-uuid>
  segment 2: start=MV-715-01 id, end=F-715A id, pipeline=<shared-uuid>

===========================
OUTPUT FORMAT
===========================

Return ONLY valid JSON, no markdown, no preamble:
{
    "nodes": [
        {
            "id_temp": "uuid",
            "level": "equipment",
            "component_name": "F-715A",
            "metadata": {
                "design_pressure_psig": 275,
                "operating_pressure_psig": 250,
                "design_temp_f": 100
            },
            "confidence": "high"
        },
        {
            "id_temp": "uuid",
            "level": "instrument",
            "component_name": "PSV-715A",
            "metadata": {
                "type": "pressure_safety_valve",
                "parent_component_name": "F-715A",
                "set_point": 275,
                "size": "3/4x1"
            },
            "confidence": "high"
        },
        {
            "id_temp": "uuid",
            "level": "valve",
            "component_name": "MV-715-01",
            "metadata": {
                "type": "manual_valve",
                "parent_component_name": "F-715A",
                "parent_pipe": "6-PL-2000-D"
            },
            "confidence": "high"
        },
        {
            "id_temp": "uuid",
            "level": "connector",
            "component_name": "connector",
            "metadata": {
                "description": "tee junction where instrument PI-715A taps into process line"
            },
            "confidence": "medium"
        },
        {
            "id_temp": "uuid",
            "level": null,
            "component_name": "off_page_endpoint",
            "metadata": {
                "destination": "TO CLOSED DRAIN TANK V-005"
            },
            "confidence": "high"
        }
    ],
    "connections": [
        {
            "id_temp": "uuid",
            "line_type": "major_process",
            "start_id": "uuid-of-V-710",
            "end_id": "uuid-of-MV-715-01",
            "pipeline": "shared-pipeline-uuid",
            "metadata": {
                "pipe_id": "6-PL-2000-D",
                "size_inches": 6
            },
            "confidence": "high"
        },
        {
            "id_temp": "uuid",
            "line_type": "major_process",
            "start_id": "uuid-of-MV-715-01",
            "end_id": "uuid-of-F-715A",
            "pipeline": "shared-pipeline-uuid",
            "metadata": {
                "pipe_id": "6-PL-2000-D",
                "size_inches": 6
            },
            "confidence": "high"
        },
        {
            "id_temp": "uuid",
            "line_type": "minor_process",
            "start_id": "uuid-of-connector",
            "end_id": "uuid-of-PSV-715A",
            "pipeline": "uuid-for-this-instrument-line",
            "metadata": {},
            "confidence": "high"
        }
    ],
    "uncertainties": "..."
}

===========================
UNCERTAINTIES
===========================

After extracting all connections, verify every node has at least one connection.
If a node has no connections, look again more carefully before marking it as isolated.

Add a top-level "uncertainties" field: a short (1-3 sentence) note on what you
found most confusing or uncertain on this page — e.g. ambiguous labels,
overlapping/crossing lines, illegible tags, or unclear connections. If nothing
was unclear, say so briefly.
"""

SOP_EXTRACTION_PROMPT = """
You are analyzing a Standard Operating Procedure (SOP) document
for an oil and gas facility.

Extract all requirements and operational rules. Classify each by rule_type:
- component_specifications: a maximum/required spec (pressure, temperature, etc.)
  for a component or group of components.
- incompatible_components: a forbidden connection between two types of components
  (e.g. "X shall not connect to Y").

For component_specifications, set component_description to the text identifying
the component(s) (e.g. "F-715 A and B Particulate Filters"), and specs to a dict
of the limits mentioned (e.g. max_pressure_psig, max_temp_f).

For incompatible_components, set component_description to null, and specs to
{"type_a": ..., "type_b": ...} using the component tags from the rule.


Return ONLY valid JSON, no markdown, no preamble:
[
    {
        "rule_type": "component_specifications",
        "raw_text": "F-715 A and B Particulate Filters: 275 psig @ 100F",
        "component_description": "F-715 A and B Particulate Filters",
        "specs": {"max_pressure_psig": 275, "max_temp_f": 100}
    },
    {
        "rule_type": "incompatible_components",
        "raw_text": "F-715 shall not connect to V-745",
        "component_description": null,
        "specs": {"type_a": "F-715", "type_b": "V-745"}
    }
]

SOP TEXT:
{sop_text}
"""

def get_sop_prompt(sop_text: str) -> str:
    return SOP_EXTRACTION_PROMPT.replace("{sop_text}", sop_text)

def get_pid_prompt() -> str:
    return PID_EXTRACTION_PROMPT_V3

